# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# == Features toggle ==================================================================================================
# Make players drop meet on death
feature-meat-player-death: false

# Make it so player with right perm can open iron doors with hands
feature-iron-door: true

# Make it so players and mobs can't trample crops
feature-farm-protection: true

# Make players faster when they are standing on certain blocks
feature-speedy-blocks: true


# == Patches ==========================================================================================================
# Prevent players from block glitching
patch-anti-block-glitching: false

# Prevent players from using ender pearls
patch-anti-ender-pearl: true


# == Teams ============================================================================================================
teams:
  red:
    name: "Team Red"
    color-code: "c"
    permission: "nationsevent.team.red"
  blue:
    name: "Team Blue"
    color-code: "b"
    permission: "nationsevent.team.blue"