
#    _   _       _   _                 ______               _
#   | \ | |     | | (_)               |  ____|             | |
#   |  \| | __ _| |_ _  ___  _ __  ___| |____   _____ _ __ | |_
#   | . ` |/ _` | __| |/ _ \| '_ \/ __|  __\ \ / / _ \ '_ \| __|
#   | |\  | (_| | |_| | (_) | | | \__ \ |___\ V /  __/ | | | |_
#   |_| \_|\__,_|\__|_|\___/|_| |_|___/______\_/ \___|_| |_|\__|



# == Main =============================================================================================================

# Event code name (Example: NG1)
# Needs to match actual build-in event codename to load event specific classes
event-codename: NS7



# == Settings =========================================================================================================

# Disable certain item crafts
# Hard coded managed from (Saves.kt file)
settings-disable-crafts: true

# Disable or limit certain enchants
# Hard coded managed from (Saves.kt file)
settings-limit-enchants: true

# Disable ender pearls usage and obtain
settings-disable-ender-pearls: true

# Disable wolf breeding
settings-disable-wolf-breeding: true

# Protect farm by disabling trembling
settings-farm-protection: true



# == Player Group Chats ===============================================================================================

# Player group chat feature toggle
pgc-enable: true

# If group chats should be saved and loaded when server restarts
pgc-save-on-server-restart: true

# Maximum amount of GCs a player can join
pgc-limit: 3

# If group chats can be used while chat is disabled
pgc-bypass-disabled-chat: true

# Colors for player group chat messages
pgc-color: "§7"
pgc-spy-color: "§8"
pgc-staff-msg-prefix: "§6[STAFF]"
pgc-name-character-limit: 6