name: NationsEvent
version: '${project.version}'
authors: [jjkay03, Gonkas77]
website: https://jjkay03.com/


main: com.jjkay03.nationsevent.NationsEvent
api-version: '1.20'
folia-supported: true


depend:
  - LuckPerms

softdepend:
  - PlaceholderAPI


permissions:
  nationsevent.use-chat:
    description: "Allows using chat"
    default: true


commands:

  #---------------------------
  #    COMMANDS : ANNOUNCE
  #---------------------------

  announcesession:
    permission: nationsevent.command.announcesession
    permission-message: "§cYou do not have permission to use this command"

  joinstage:
    permission: nationsevent.command.joinstage
    permission-message: "§cYou do not have permission to use this command"

  joinvc:
    permission: nationsevent.command.joinvc
    permission-message: "§cYou do not have permission to use this command"

  permanentmessage:
    aliases: [ permmsg, permmessage]
    permission: nationsevent.command.permanentmessage
    permission-message: "§cYou do not have permission to use this command"

  #---------------------------
  #   COMMANDS : MANAGEMENT
  #---------------------------

  sessiontime:
    permission: nationsevent.command.sessiontime
    permission-message: "§cYou do not have permission to use this command"

  randomplayertp:
    aliases: [ rptp, tprandomplayer]
    permission: nationsevent.command.randomplayertp
    permission-message: "§cYou do not have permission to use this command"

  pvptoggle:
    aliases: [ pvp, togglepvp ]
    permission: nationsevent.command.pvptoggle
    permission-message: "§cYou do not have permission to use this command"

  freezeall:
    permission: nationsevent.command.freezeall
    permission-message: "§cYou do not have permission to use this command"

  globalchat:
    aliases: [ chattoggle, togglechat ]
    permission: nationsevent.command.globalchat
    permission-message: "§cYou do not have permission to use this command"

  #---------------------------
  #     COMMANDS : OTHERS
  #---------------------------

  smite:
    permission: nationsevent.command.smite
    permission-message: "§cYou do not have permission to use this command"

  hidestaff:
    permission: nationsevent.command.hidestaff
    permission-message: "§cYou do not have permission to use this command"

  #---------------------------
  #  COMMANDS : PLAYER SCALE
  #---------------------------

  playerscale:
    aliases: [ pscale ]
    permission: nationsevent.command.playerscale
    permission-message: "§cYou do not have permission to use this command"

  playerscalerestall:
    aliases: [ pscaleresetall ]
    permission: nationsevent.command.playerscalerestall
    permission-message: "§cYou do not have permission to use this command"

  #---------------------------
  #   COMMANDS : PLAYER GC
  #---------------------------

  groupchat:
    aliases: [ gc, playergroupchats ]
    permission: nationsevent.command.groupchat
    permission-message: "§cYou do not have permission to use this command"

  admingroupchat:
    aliases: [ agc, admingc ]
    permission: nationsevent.command.admingroupchat
    permission-message: "§cYou do not have permission to use this command"


  #---------------------------
  #   COMMANDS : VOICE CHAT
  #---------------------------

  voicechatperms:
    aliases: [ vcperms, voicechattoggle, vctoggle, togglevoicechat, togglevc ]
    permission: nationsevent.command.voicechatperms
    permission-message: "§cYou do not have permission to use this command"

  groupvoicechatperms:
    aliases: [ gvcperms, gvctoggle, togglegvc ]
    permission: nationsevent.command.groupvoicechatperms
    permission-message: "§cYou do not have permission to use this command"


# =====================================================================================================================
#                    SEASON SPECIFIC COMMANDS SEPARATOR  /  SEASON SPECIFIC COMMANDS UNDER!
# =====================================================================================================================

