name: NationsEvent
version: '${project.version}'
authors: [jjkay03, Gonkas77]
website: https://jjkay03.com/


main: com.jjkay03.nationsevent.NationsEvent
api-version: '1.21'
folia-supported: true


depend:
  - LuckPerms
  - voicechat

softdepend:
  - PlaceholderAPI


permissions:
  nationsevent.use-chat:
    description: "Allows using chat"
    default: true


commands:

  #--------------------------------
  #      COMMANDS : ANNOUNCE
  #--------------------------------

  announcesession:
    permission: nationsevent.command.announcesession
    permission-message: "§cYou do not have permission to use this command"

  joinstage:
    permission: nationsevent.command.joinstage
    permission-message: "§cYou do not have permission to use this command"

  joinvc:
    permission: nationsevent.command.joinvc
    permission-message: "§cYou do not have permission to use this command"

  permanentmessage:
    aliases: [ permmsg, permmessage]
    permission: nationsevent.command.permanentmessage
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #     COMMANDS : MANAGEMENT
  #--------------------------------

  sessiontime:
    permission: nationsevent.command.sessiontime
    permission-message: "§cYou do not have permission to use this command"

  pvptoggle:
    aliases: [ pvp, togglepvp ]
    permission: nationsevent.command.pvptoggle
    permission-message: "§cYou do not have permission to use this command"

  freezeall:
    permission: nationsevent.command.freezeall
    permission-message: "§cYou do not have permission to use this command"

  globalchat:
    aliases: [ chattoggle, togglechat ]
    permission: nationsevent.command.globalchat
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #       COMMANDS : OTHERS
  #--------------------------------

  smite:
    permission: nationsevent.command.smite
    permission-message: "§cYou do not have permission to use this command"

  hidestaff:
    permission: nationsevent.command.hidestaff
    permission-message: "§cYou do not have permission to use this command"

  gamemode:
    aliases: [ gm ]
    permission: nationsevent.command.gamemode
    permission-message: "§cYou do not have permission to use this command"

  fly:
    permission: nationsevent.command.fly
    permission-message: "§cYou do not have permission to use this command"

  god:
    permission: nationsevent.command.god
    permission-message: "§cYou do not have permission to use this command"

  sudo:
    permission: nationsevent.command.sudo
    permission-message: "§cYou do not have permission to use this command"

  heal:
    permission: nationsevent.command.heal
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #  COMMANDS : PLAYER ASSISTANCE
  #--------------------------------

  needstaff:
    permission: nationsevent.command.needsatff
    permission-message: "§cYou do not have permission to use this command"

  needstaffmanage:
    aliases: [ nsmanage ]
    permission: nationsevent.command.needsatffmanage
    permission-message: "§cYou do not have permission to use this command"

  needrecord:
    permission: nationsevent.command.needrecord
    permission-message: "§cYou do not have permission to use this command"

  needrecordmanage:
    aliases: [ nrmanage ]
    permission: nationsevent.command.needrecordmanage
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #    COMMANDS : PLAYER SCALE
  #--------------------------------

  playerscale:
    aliases: [ pscale ]
    permission: nationsevent.command.playerscale
    permission-message: "§cYou do not have permission to use this command"

  playerscalerestall:
    aliases: [ pscaleresetall ]
    permission: nationsevent.command.playerscalerestall
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #  COMMANDS : PLAYER GROUP CHAT
  #--------------------------------

  groupchat:
    aliases: [ gc, playergroupchats ]
    permission: nationsevent.command.groupchat
    permission-message: "§cYou do not have permission to use this command"

  admingroupchat:
    aliases: [ agc, admingc ]
    permission: nationsevent.command.admingroupchat
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #      COMMANDS : TELEPORT
  #--------------------------------

  teleportback:
    aliases: [ tpb, tpback, back ]
    permission: nationsevent.command.teleportback
    permission-message: "§cYou do not have permission to use this command"

  teleporthere:
    aliases: [ tph, tphere ]
    permission: nationsevent.command.teleporthere
    permission-message: "§cYou do not have permission to use this command"

  teleportjump:
    aliases: [ tpj, tpjump, jump ]
    permission: nationsevent.command.teleportjump
    permission-message: "§cYou do not have permission to use this command"

  teleportplayer:
    aliases: [ tp, tpp, tpplayer ]
    permission: nationsevent.command.teleportplayer
    permission-message: "§cYou do not have permission to use this command"

  teleportposition:
    aliases: [ tppos, tpposition ]
    permission: nationsevent.command.teleportposition
    permission-message: "§cYou do not have permission to use this command"

  teleportrandomplayer:
    aliases: [ tprp, tprandomplayer, randomplayertp ]
    permission: nationsevent.command.teleportrandomplayer
    permission-message: "§cYou do not have permission to use this command"

  teleportworld:
    aliases: [ tpworld ]
    permission: nationsevent.command.teleportworld
    permission-message: "§cYou do not have permission to use this command"

  teleporttop:
    aliases: [ top, tptop ]
    permission: nationsevent.command.teleporttop
    permission-message: "§cYou do not have permission to use this command"

  teleportoffline:
    aliases: [ tpo, tpoffline ]
    permission: nationsevent.command.teleportoffline
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #      COMMANDS : UTILITY
  #--------------------------------

  listluckpermsgroups:
    aliases: [ listlpgroups ]
    permission: nationsevent.command.listluckpermsgroups
    permission-message: "§cYou do not have permission to use this command"

  listworlds:
    permission: nationsevent.command.listworlds
    permission-message: "§cYou do not have permission to use this command"

  liststates:
    aliases: [ ls ]
    permission: nationsevent.command.liststates
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #     COMMANDS : VOICE CHAT
  #--------------------------------

  voicechatperms:
    aliases: [ vcperms, voicechattoggle, vctoggle, togglevoicechat, togglevc ]
    permission: nationsevent.command.voicechatperms
    permission-message: "§cYou do not have permission to use this command"

  groupvoicechatperms:
    aliases: [ gvcperms, gvctoggle, togglegvc ]
    permission: nationsevent.command.groupvoicechatperms
    permission-message: "§cYou do not have permission to use this command"

  #---------------------------------------
  #  COMMANDS : (Not in commands folder)
  #---------------------------------------

  worldsbridge:
    permission: nationsevent.command.worldsbridge
    permission-message: "§cYou do not have permission to use this command"

  #--------------------------------
  #    COMMANDS : INTEGRATIONS
  #--------------------------------

  broadcastvoice:
    permission: nationsevent.command.broadcastvoice
    permission-message: "§cYou do not have permission to use this command"


# =====================================================================================================================
#                    SEASON SPECIFIC COMMANDS SEPARATOR  /  SEASON SPECIFIC COMMANDS UNDER!
# =====================================================================================================================

  preferredteam:
    permission: nationsevent.command.preferredteam
    permission-message: "§cYou do not have permission to use this command"

  applypreferredteam:
    permission: nationsevent.command.applypreferredteam
    permission-message: "§cYou do not have permission to use this command"

  assignrandomteam:
    permission: nationsevent.command.assignrandomteam
    permission-message: "§cYou do not have permission to use this command"

  gotoisland:
    permission: nationsevent.command.gotoisland
    permission-message: "§cYou do not have permission to use this command"

  queuetoisland:
    permission: nationsevent.command.queuetoisland
    permission-message: "§cYou do not have permission to use this command"