name: NationsEvent
version: '${project.version}'
authors: [jjkay03]
website: https://jjkay03.com/

depend:
  - TAB

main: com.jjkay03.nationsevent.NationsEvent
api-version: '1.20'

commands:
  joinvc:
    permission: nationsevent.command.joinvc
    permission-message: "You do not have permission to use this command"

  joinstage:
    permission: nationsevent.command.joinstage
    permission-message: "You do not have permission to use this command"

  announcesession:
    permission: nationsevent.command.announcesession
    permission-message: "You do not have permission to use this command"

  sessiontime:
    permission: nationsevent.command.sessiontime
    permission-message: "You do not have permission to use this command"

  pvptoggle:
    permission: nationsevent.command.pvptoggle
    permission-message: "You do not have permission to use this command"

  pvpalerts:
    permission: nationsevent.command.pvpalerts
    permission-message: "You do not have permission to use this command"

  voicechatperms:
    permission: nationsevent.command.voicechatperms
    permission-message: "You do not have permission to use this command"

  bypassviewdistance:
    permission: nationsevent.command.bypassviewdistance
    permission-message: "You do not have permission to use this command"

  vote:
    permission: nationsevent.command.vote
    permission-message: "You do not have permission to use this command"

  topvotes:
    permission: nationsevent.command.topvotes
    permission-message: "You do not have permission to use this command"

  clearvotes:
    permission: nationsevent.command.clearvotes
    permission-message: "You do not have permission to use this command"

  exportvotes:
    permission: nationsevent.command.exportvotes
    permission-message: "You do not have permission to use this command"

  lockvotes:
    permission: nationsevent.command.lockvotes
    permission-message: "You do not have permission to use this command"

  playerscale:
    aliases: [pscale]
    permission: nationsevent.command.playerscale
    permission-message: "You do not have permission to use this command"

  playerscalerestall:
    aliases: [pscaleresetall]
    permission: nationsevent.command.playerscalerestall
    permission-message: "You do not have permission to use this command"

  needadmin:
    aliases: [nadmin]
    permission: nationsevent.command.needadmin
    permission-message: "You do not have permission to use this command"

  freezeall:
    permission: nationsevent.command.freezeall
    permission-message: "You do not have permission to use this command"

  hidestaff:
    permission: nationsevent.command.hidestaff
    permission-message: "You do not have permission to use this command"

  fullmoon:
    permission: nationsevent.command.fullmoon
    permission-message: "You do not have permission to use this command"

  bearrage:
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"

  wolfrage:
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"

  wolfrageall:
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"

  globalblindness:
    aliases: [gblindness]
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"

  rollroles:
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"

  role:
    permission: nationsevent.command.ng4.role
    permission-message: "You do not have permission to use this command"

  clericimmunity:
    aliases: [cleticimmun]
    permission: nationsevent.admin
    permission-message: "You do not have permission to use this command"